import { AlertTriangle, Lightbulb, Sparkles } from "lucide-react"
import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import { PageHeader } from "@/components/layout/page-header"
import { Badge } from "@/components/ui/badge"
import { useBusiness } from "@/features/business/business-context"
import { getOpportunityAdvice } from "@/features/opportunities/opportunity-service"
import { opportunityErrorMessage, OpportunityDataError, type AdvisorResponse, type OpportunitySignal, type OpportunitySignalType } from "@/features/opportunities/opportunity-types"
import { useOpportunitySnapshot } from "@/features/opportunities/opportunity-queries"

const typeLabels: Record<OpportunitySignalType, string> = { RESTOCK_DEMAND: "Restock Demand", SALES_MOMENTUM: "Sales Momentum", SLOW_MOVING_STOCK: "Slow-Moving Stock", MARGIN_ATTENTION: "Margin Attention", REPEATED_PURCHASE_DEMAND: "Repeated Purchase Demand" }
export function OpportunitiesPage() {
  const { business, enabledModules, role } = useBusiness(); const query = useOpportunitySnapshot(); const [advisor, setAdvisor] = useState<AdvisorResponse | null>(null); const [advisorError, setAdvisorError] = useState<string | null>(null); const [isPending, setIsPending] = useState(false); const [focus, setFocus] = useState("")
  useEffect(() => {
    // A workspace switch must never retain generated guidance from the previous business.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setAdvisor(null); setAdvisorError(null); setFocus(""); setIsPending(false)
  }, [business?.id])
  const requestAdvice = async (signalId?: string) => {
    if (!business || isPending) return
    setIsPending(true); setAdvisorError(null); setFocus(signalId ?? "")
    try { setAdvisor(await getOpportunityAdvice({ businessId: business.id, ...(signalId ? { signalId } : {}) })) }
    catch (cause) { setAdvisorError(cause instanceof OpportunityDataError ? cause.message : opportunityErrorMessage()) }
    finally { setIsPending(false) }
  }
  if (!enabledModules.includes("smart_insights") || !["owner", "manager"].includes(role ?? "")) return null
  return <section aria-labelledby="opportunities-heading" className="space-y-6">
    <PageHeader description="Review signals found in recorded StockPilot data. These are review opportunities, not predictions or guarantees." eyebrow="Deterministic business intelligence" title="Business Opportunities" titleId="opportunities-heading" />
    {query.isLoading && <div className="flex min-h-56 items-center justify-center rounded-xl border border-border bg-card" role="status"><span aria-hidden="true" className="mr-3 size-5 animate-spin rounded-full border-2 border-border border-t-primary" />Loading Business Opportunities…</div>}
    {query.isError && !query.isLoading && <div className="rounded-xl border border-destructive/25 bg-card p-8 text-center" role="alert"><AlertTriangle aria-hidden="true" className="mx-auto size-8 text-destructive" /><h2 className="mt-3 text-lg font-semibold">Business Opportunities unavailable</h2><p className="mt-2 text-muted-foreground">We couldn't load the deterministic opportunity signals.</p><Button className="mt-5" onClick={() => void query.refetch()} variant="outline">Try again</Button></div>}
    {query.data && !query.isError && <>
      <div className="rounded-xl border border-border bg-card p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Recorded-data review signals</h2><p className="mt-1 text-sm text-muted-foreground">Priority and evidence below come directly from the deterministic opportunity engine.</p></div><span className="text-sm text-muted-foreground">{query.data.selection.returnedSignals} of {query.data.selection.totalSignals} returned</span></div>{query.data.selection.truncated && <p className="mt-3 text-xs text-muted-foreground">Some eligible signals are not shown because the deterministic result is bounded.</p>}</div>
      {query.data.signals.length === 0 ? <EmptyState /> : <div className="space-y-4">{query.data.signals.map((signal) => <OpportunityCard key={signal.signalId} signal={signal} onGuidance={() => void requestAdvice(signal.signalId)} disabled={isPending} />)}</div>}
      <section className="rounded-xl border border-primary/20 bg-primary/5 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 font-semibold"><Sparkles aria-hidden="true" className="size-4" />Optional AI guidance</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Ask the grounded advisor to explain these deterministic signals and suggest actions to consider. AI guidance does not change priority or evidence.</p>{query.data.signals.length === 0 && <p className="mt-2 text-sm text-muted-foreground">AI guidance becomes available when StockPilot identifies at least one deterministic opportunity.</p>}</div><Button disabled={isPending || query.data.signals.length === 0} onClick={() => void requestAdvice()}>{isPending ? "Preparing guidance…" : "Get AI Guidance"}</Button></div>{advisorError && <p className="mt-4 rounded-lg border border-destructive/25 bg-destructive/5 p-3 text-sm text-destructive" role="alert">{advisorError}</p>}</section>
      {advisor && <AdvisorResult result={advisor} focusedSignalId={focus} />}
    </>}
  </section>
}

function EmptyState() { return <div className="rounded-xl border border-dashed border-border bg-card p-10 text-center"><Lightbulb aria-hidden="true" className="mx-auto size-10 text-muted-foreground" /><h2 className="mt-4 text-lg font-semibold">No eligible opportunities right now</h2><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">The deterministic engine did not find a review signal in the available completed periods. This does not mean there is no business activity.</p></div> }

function OpportunityCard({ signal, onGuidance, disabled }: { signal: OpportunitySignal; onGuidance: () => void; disabled: boolean }) { return <article className="rounded-xl border border-border bg-card p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="text-xs font-medium uppercase tracking-wide text-primary">{typeLabels[signal.type]}</p><h2 className="mt-1 text-lg font-semibold">{signal.title}</h2><p className="mt-2 text-sm text-muted-foreground">{signal.summary}</p></div><Badge variant={signal.priority === "HIGH" ? "destructive" : signal.priority === "MEDIUM" ? "warning" : "neutral"}>{signal.priority} priority</Badge></div><div className="mt-5 grid gap-4 border-t border-border pt-4 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Product</p><p className="mt-1 font-medium">{signal.product.name}</p><p className="text-xs text-muted-foreground">SKU {signal.product.sku ?? "Not provided"}</p></div><div><p className="text-xs text-muted-foreground">Observation period</p><p className="mt-1 text-sm">{signal.observationPeriod.startDate} to {signal.observationPeriod.endDate}</p>{signal.comparisonPeriod && <p className="mt-1 text-xs text-muted-foreground">Compared with {signal.comparisonPeriod.startDate} to {signal.comparisonPeriod.endDate}</p>}</div></div><div className="mt-5 border-t border-border pt-4"><p className="text-xs font-medium text-muted-foreground">Deterministic evidence</p><dl className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(signal.evidence).map(([key, value]) => <div key={key}><dt className="text-xs text-muted-foreground">{key}</dt><dd className="mt-1 break-all font-medium tabular-nums">{String(value)}</dd></div>)}</dl></div><div className="mt-5 flex flex-col gap-3 border-t border-border pt-4 sm:flex-row sm:items-center sm:justify-between"><div className="text-xs text-muted-foreground"><p>{signal.limitations[0]}</p>{signal.limitations.length > 1 && <p className="mt-1">{signal.limitations.length - 1} more limitation{signal.limitations.length === 2 ? "" : "s"}.</p>}</div><Button disabled={disabled} onClick={onGuidance} variant="outline">{disabled ? "Preparing…" : "Explain this signal"}</Button></div></article> }

function AdvisorResult({ result, focusedSignalId }: { result: AdvisorResponse; focusedSignalId: string }) { const opportunities = focusedSignalId ? result.opportunities.filter((item) => item.signalId === focusedSignalId) : result.opportunities; return <section aria-label="AI opportunity guidance" className="space-y-4"><div className="rounded-xl border border-primary/20 bg-card p-5 shadow-sm"><h2 className="font-semibold">Grounded AI guidance</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{result.summary}</p><p className="mt-4 text-xs text-muted-foreground">The deterministic StockPilot signals and hydrated evidence remain authoritative. Suggested actions are for review and are not guaranteed outcomes.</p></div>{opportunities.map((item) => <article className="rounded-xl border border-border bg-card p-5" key={item.signalId}><h3 className="font-semibold">{item.signalId}</h3><p className="mt-3 text-sm leading-7">{item.explanation}</p>{item.suggestedActions.length > 0 && <><h4 className="mt-4 text-sm font-medium">Actions to consider</h4><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-muted-foreground">{item.suggestedActions.map((action) => <li key={action}>{action}</li>)}</ul></>}{item.evidence.length > 0 && <><h4 className="mt-4 text-sm font-medium">Validated evidence</h4><dl className="mt-2 grid gap-3 sm:grid-cols-2">{item.evidence.map((evidence) => <div key={evidence.id}><dt className="text-xs text-muted-foreground">{evidence.label}</dt><dd className="mt-1 break-all font-medium tabular-nums">{evidence.value}</dd></div>)}</dl></>}{item.limitations.length > 0 && <p className="mt-4 text-xs text-muted-foreground">{item.limitations.join(" ")}</p>}</article>)}{result.overallLimitations.length > 0 && <div className="rounded-xl border border-amber-500/35 bg-amber-500/5 p-4"><h2 className="font-semibold">Guidance limitations</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-muted-foreground">{result.overallLimitations.map((limitation) => <li key={limitation}>{limitation}</li>)}</ul></div>}</section> }
