import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { MemoryRouter } from "react-router-dom"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { createBusinessValue, testBusiness, TestBusinessProvider } from "@/test/auth-test-utils"
import { PurchasingSuppliersPage } from "@/pages/purchasing-suppliers-page"

const mocks=vi.hoisted(()=>({ create:vi.fn(),update:vi.fn(),setActive:vi.fn(), data:[{id:"s1",name:"Supplier A",contactName:"Jamie",phone:null,email:"a@example.com",notes:null,isActive:true},{id:"s2",name:"Supplier B",contactName:null,phone:null,email:null,notes:null,isActive:false}] as Array<{id:string;name:string;contactName:string|null;phone:string|null;email:string|null;notes:string|null;isActive:boolean}> }))
vi.mock("@/features/purchasing/purchasing-queries",()=>({useManagedSuppliers:()=>({data:mocks.data,isLoading:false,isError:false,refetch:vi.fn()}),useSupplierMutations:()=>({create:{mutateAsync:mocks.create,isPending:false},update:{mutateAsync:mocks.update,isPending:false},setActive:{mutateAsync:mocks.setActive,isPending:false}})}))
function renderPage(role:"owner"|"manager"|"employee"="owner"){return render(<TestBusinessProvider value={createBusinessValue({business:testBusiness,role,enabledModules:["purchasing"]})}><MemoryRouter><PurchasingSuppliersPage/></MemoryRouter></TestBusinessProvider>)}
describe("purchasing suppliers page",()=>{beforeEach(()=>{mocks.data=[{id:"s1",name:"Supplier A",contactName:"Jamie",phone:null,email:"a@example.com",notes:null,isActive:true},{id:"s2",name:"Supplier B",contactName:null,phone:null,email:null,notes:null,isActive:false}];mocks.create.mockReset().mockResolvedValue(undefined);mocks.update.mockReset().mockResolvedValue(undefined);mocks.setActive.mockReset().mockResolvedValue(undefined)});afterEach(cleanup)
 it("shows employees read-only with no management actions",()=>{renderPage("employee");expect(screen.getByText("Supplier A")).toBeInTheDocument();expect(screen.queryByRole("button",{name:/add supplier/i})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:/edit/i})).not.toBeInTheDocument()})
 it("filters active/inactive and searches contact details",async()=>{const u=userEvent.setup();renderPage();expect(screen.getByText("Supplier A")).toBeInTheDocument();expect(screen.queryByText("Supplier B")).not.toBeInTheDocument();await u.selectOptions(screen.getByLabelText("Status"),"all");await u.type(screen.getByRole("searchbox"),"Jamie");expect(screen.getByText("Supplier A")).toBeInTheDocument();expect(screen.queryByText("Supplier B")).not.toBeInTheDocument()})
 it("requires a name and allows duplicate names on create",async()=>{const u=userEvent.setup();renderPage();await u.click(screen.getByRole("button",{name:/add supplier/i}));await u.click(screen.getByRole("button",{name:/save supplier/i}));expect(screen.getByRole("alert")).toHaveTextContent(/name is required/i);fireEvent.change(screen.getByLabelText(/supplier name/i),{target:{value:" Supplier A "}});await u.click(screen.getByRole("button",{name:/save supplier/i}));await waitFor(()=>expect(mocks.create).toHaveBeenCalledWith({name:"Supplier A",contact_name:null,phone:null,email:null,notes:null}))})
 it("updates and deactivates without deleting supplier",async()=>{const u=userEvent.setup();renderPage();await u.click(screen.getByRole("button",{name:"Edit"}));fireEvent.change(screen.getByLabelText(/supplier name/i),{target:{value:"Renamed"}});await u.click(screen.getByRole("button",{name:/save supplier/i}));await waitFor(()=>expect(mocks.update).toHaveBeenCalledWith({id:"s1",input:expect.objectContaining({name:"Renamed"})}));await u.click(screen.getByRole("button",{name:"Deactivate"}));expect(mocks.setActive).toHaveBeenCalledWith({id:"s1",active:false})})
})
