import { useMemo, useState } from "react"
import { Link } from "react-router-dom"
import { Button } from "@/components/ui/button"
import { PurchasingSectionNav } from "@/components/purchasing/purchasing-section-nav"
import { useBusiness } from "@/features/business/business-context"
import { formatPurchaseMoney } from "@/features/purchasing/purchasing-money"
import { usePurchaseHistory } from "@/features/purchasing/purchasing-queries"
import type { PurchaseSummary } from "@/features/purchasing/purchasing-types"

function validDate(value: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return ""; const d = new Date(`${value}T00:00:00Z`); return Number.isNaN(d.getTime()) || d.toISOString().slice(0,10)!==value ? "" : value }
function showDate(value: string) { const d = new Date(value); return Number.isNaN(d.getTime()) ? "Date unavailable" : new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(d) }
function ViewLink({purchase}: {purchase: PurchaseSummary}) { return <Button asChild size="sm" variant="outline"><Link aria-label={`View purchase ${purchase.purchaseReference}`} to={`/purchasing/${purchase.id}`}>View</Link></Button> }

export function PurchaseHistoryPage() {
 const {business}=useBusiness(); const query=usePurchaseHistory(); const [q,setQ]=useState(""); const [from,setFrom]=useState(""); const [to,setTo]=useState("")
 const reversed=Boolean(from&&to&&from>to), safeFrom=reversed?"":validDate(from),safeTo=reversed?"":validDate(to)
 const rows=useMemo(()=>{const term=q.trim().toLocaleLowerCase();return(query.data??[]).filter(p=>{const date=p.receivedAt.slice(0,10);const matches=!term||p.purchaseReference.toLocaleLowerCase().includes(term)||(p.supplierName??"").toLocaleLowerCase().includes(term)||p.items.some(i=>i.productName.toLocaleLowerCase().includes(term)||(i.productSku??"").toLocaleLowerCase().includes(term));return matches&&(!safeFrom||date>=safeFrom)&&(!safeTo||date<=safeTo)})},[query.data,q,safeFrom,safeTo])
 const clear=()=>{setQ("");setFrom("");setTo("")}; const hasFilters=Boolean(q||from||to)
 return <section className="space-y-6"><PurchasingSectionNav/><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Purchasing</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Purchase history</h1><p className="mt-2 text-muted-foreground">Review received stock and its recorded costs.</p></div><Button asChild><Link to="/purchasing">Receive stock</Link></Button></header>
 <section aria-label="Filter purchases" className="grid gap-3 rounded-xl border border-border bg-card p-4 sm:grid-cols-[minmax(0,1fr)_repeat(2,minmax(150px,.35fr))_auto] sm:items-end"><label className="space-y-1.5 text-sm"><span>Search purchases</span><input className="h-10 w-full rounded-md border border-border bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-primary/20" onChange={e=>setQ(e.target.value.slice(0,120))} placeholder="Reference, supplier, product or SKU" type="search" value={q}/></label><label className="space-y-1.5 text-sm"><span>From date</span><input className="h-10 w-full rounded-md border border-border bg-background px-3" onChange={e=>setFrom(e.target.value)} type="date" value={safeFrom}/></label><label className="space-y-1.5 text-sm"><span>To date</span><input className="h-10 w-full rounded-md border border-border bg-background px-3" onChange={e=>setTo(e.target.value)} type="date" value={safeTo}/></label>{hasFilters&&<Button onClick={clear} variant="outline">Clear filters</Button>}</section>
 {reversed&&<p className="text-sm text-muted-foreground" role="status">The date range was reversed, so date filters were cleared.</p>}
 {query.isLoading&&<p className="rounded-xl border p-8 text-center" role="status">Loading purchase history…</p>}{query.isError&&<section className="rounded-xl border border-destructive/25 p-8 text-center" role="alert"><h2 className="font-semibold">Purchase history unavailable</h2><Button className="mt-3" onClick={()=>void query.refetch()} variant="outline">Try again</Button></section>}
 {!query.isLoading&&!query.isError&&query.data?.length===0&&<div className="rounded-xl border border-dashed p-10 text-center"><h2 className="font-semibold">No purchases yet</h2><p className="mt-2 text-sm text-muted-foreground">Completed receipts will appear here.</p><Button asChild className="mt-4"><Link to="/purchasing">Receive stock</Link></Button></div>}
 {!query.isLoading&&!query.isError&&query.data?.length&&!rows.length&&<div className="rounded-xl border border-dashed p-10 text-center"><h2 className="font-semibold">No matching purchases</h2><p className="mt-2 text-sm text-muted-foreground">Try changing or clearing your filters.</p><Button className="mt-4" onClick={clear} variant="outline">Clear filters</Button></div>}
 {rows.length>0&&business&&<><p className="text-sm text-muted-foreground">{rows.length} {rows.length===1?"purchase":"purchases"}. History is currently loaded as a single client-side list; revisit server pagination as data scales in Phase 5D.</p><div className="hidden overflow-x-auto rounded-xl border border-border bg-card md:block"><table className="w-full text-left"><caption className="sr-only">Purchase history</caption><thead className="border-b bg-muted/60 text-xs uppercase tracking-wide text-muted-foreground"><tr>{["Purchase","Date and time","Supplier","Items","Recorded by","Total","Action"].map(h=><th className="px-4 py-3 font-medium" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(p=><tr className="border-b last:border-0" key={p.id}><td className="px-4 py-3"><Link className="font-medium text-primary hover:underline" to={`/purchasing/${p.id}`}>{p.purchaseReference}</Link></td><td className="px-4 py-3 text-sm">{showDate(p.receivedAt)}</td><td className="px-4 py-3 text-sm">{p.supplierName||"No supplier"}</td><td className="px-4 py-3 text-sm">{p.itemCount}</td><td className="px-4 py-3 text-sm">Team member</td><td className="px-4 py-3 text-right font-medium tabular-nums">{formatPurchaseMoney(p.total,business.currency)}</td><td className="px-4 py-3 text-right"><ViewLink purchase={p}/></td></tr>)}</tbody></table></div><ul aria-label="Purchase history" className="space-y-3 md:hidden">{rows.map(p=><li className="rounded-xl border bg-card p-4" key={p.id}><div className="flex justify-between gap-3"><div className="min-w-0"><Link className="break-all font-semibold text-primary" to={`/purchasing/${p.id}`}>{p.purchaseReference}</Link><p className="mt-1 text-sm text-muted-foreground">{showDate(p.receivedAt)}</p></div><span className="shrink-0 font-semibold tabular-nums">{formatPurchaseMoney(p.total,business.currency)}</span></div><p className="mt-3 text-sm text-muted-foreground">{p.supplierName||"No supplier"} · {p.itemCount} {p.itemCount===1?"item":"items"} · Team member</p><ViewLink purchase={p}/></li>)}</ul></>}
 </section>
}
