import { render, screen } from "@testing-library/react"
import { MemoryRouter, Route, Routes } from "react-router-dom"
import { describe, expect, it, vi } from "vitest"
import { PurchaseDetailPage } from "@/pages/purchase-detail-page"
import { createBusinessValue, testBusiness, TestBusinessProvider } from "@/test/auth-test-utils"

const mock=vi.hoisted(()=>({data:{id:"id",purchaseReference:"PUR-000010",receivedAt:"2026-06-02T10:30:00Z",supplierName:"ABC Wholesale",subtotal:"12.5000",total:"12.5000",notes:"Initial receipt",items:[{id:"i",productName:"USB Cable",productSku:"USB-01",quantity:"1",unitCost:"12.5000",lineTotal:"12.5000"}] } as null|{id:string;purchaseReference:string;receivedAt:string;supplierName:string|null;subtotal:string;total:string;notes:string|null;items:Array<{id:string;productName:string;productSku:string|null;quantity:string;unitCost:string;lineTotal:string}>}, id:vi.fn()}))
vi.mock("@/features/purchasing/purchasing-queries",()=>({usePurchaseDetail:(id:string)=>{mock.id(id);return {data:mock.data,isLoading:false,isError:false,refetch:vi.fn()}}}))
describe("purchase detail",()=>{it("uses immutable supplier/product/SKU/cost snapshots and business-scoped ID hook",()=>{render(<TestBusinessProvider value={createBusinessValue({business:testBusiness,enabledModules:["purchasing"]})}><MemoryRouter initialEntries={["/purchasing/purchase-10"]}><Routes><Route path="/purchasing/:purchaseId" element={<PurchaseDetailPage/>}/></Routes></MemoryRouter></TestBusinessProvider>);expect(mock.id).toHaveBeenCalledWith("purchase-10");expect(screen.getByText("ABC Wholesale")).toBeInTheDocument();expect(screen.getByText("USB Cable")).toBeInTheDocument();expect(screen.getByText("SKU USB-01")).toBeInTheDocument();expect(screen.getAllByText(/US\$12\.50/).length).toBeGreaterThan(0);expect(screen.getByText("Initial receipt")).toBeInTheDocument()});it("shows neutral unavailable state for missing/inaccessible purchases",()=>{mock.data=null;render(<TestBusinessProvider value={createBusinessValue({business:testBusiness,enabledModules:["purchasing"]})}><MemoryRouter><PurchaseDetailPage/></MemoryRouter></TestBusinessProvider>);expect(screen.getByRole("heading",{name:"Purchase unavailable"})).toBeInTheDocument();expect(screen.getByText(/unavailable or could not be found/i)).toBeInTheDocument()})})
