import { Download, Printer } from "lucide-react"
import { useMemo, useState } from "react"
import { Button } from "@/components/ui/button"
import { useBusiness } from "@/features/business/business-context"
import { getReportDateRange, type ReportPeriodPreset } from "@/features/reports/report-period"
import { useReport } from "@/features/reports/report-queries"
import { downloadCsv, toCsv } from "@/features/reports/report-csv"
import type { ReportType } from "@/features/reports/report-types"

const labels: Record<ReportType, string> = { inventory: "Inventory Report", inventory_movements: "Inventory Movement Report", sales: "Sales Report", purchasing: "Purchasing Report", expenses: "Expenses & Profitability Report" }
const presets: Array<[ReportPeriodPreset, string]> = [["today", "Today"], ["yesterday", "Yesterday"], ["this_week", "This week"], ["last_week", "Last week"], ["this_month", "This month"], ["last_month", "Last month"], ["last_30_days", "Last 30 days"], ["last_90_days", "Last 90 days"], ["custom", "Custom"]]
const inputClass = "h-10 w-full rounded-md border border-border bg-background px-3 text-sm outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/20"

export function ReportsPage() {
  const { business, enabledModules, role } = useBusiness()
  const available = useMemo<ReportType[]>(() => ["inventory", "inventory_movements", ...(enabledModules.includes("sales") && ["owner", "manager", "employee"].includes(role ?? "") ? ["sales" as const] : []), ...(enabledModules.includes("purchasing") && ["owner", "manager", "employee"].includes(role ?? "") ? ["purchasing" as const] : []), ...(enabledModules.includes("expenses") && ["owner", "manager"].includes(role ?? "") ? ["expenses" as const] : [])], [enabledModules, role])
  const [type, setType] = useState<ReportType>("inventory")
  const [preset, setPreset] = useState<ReportPeriodPreset>("this_month")
  const [customStart, setCustomStart] = useState(""); const [customEnd, setCustomEnd] = useState(""); const [page, setPage] = useState(1)
  const selectedType = available.includes(type) ? type : (available[0] ?? "inventory")
  const range = useMemo(() => getReportDateRange(preset, business?.timezone ?? "UTC", new Date(), customStart, customEnd), [business?.timezone, customEnd, customStart, preset])
  const report = useReport(selectedType, range, available.includes(selectedType), page)
  const columns = report.data?.rows[0] ? Object.keys(report.data.rows[0]).map((key) => ({ key, label: key.replace(/([A-Z])/g, " $1").replace(/^./, (value) => value.toUpperCase()), text: !["itemCount", "totalRows"].includes(key) })) : []
  const exportReport = () => { if (!report.data) return; const csv = toCsv(columns, report.data.rows); downloadCsv(`stockpilot-${selectedType}-${report.data.startDate}-to-${report.data.endDate}.csv`, csv) }
  return <section className="space-y-6 print:space-y-3">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Operational reporting</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Reports</h1><p className="mt-2 text-muted-foreground">Bounded reports from recorded StockPilot data.</p></div><div className="flex gap-2 print:hidden"><Button disabled={!report.data} onClick={exportReport} variant="outline"><Download aria-hidden="true" className="mr-2 size-4" />CSV</Button><Button onClick={() => window.print()} variant="outline"><Printer aria-hidden="true" className="mr-2 size-4" />Print</Button></div></header>
    <section aria-label="Report controls" className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-3 sm:items-end print:hidden"><label className="space-y-1.5 text-sm"><span>Report</span><select aria-label="Report type" className={inputClass} onChange={(event) => { setType(event.target.value as ReportType); setPage(1) }} value={type}>{available.map((item) => <option key={item} value={item}>{labels[item]}</option>)}</select></label><label className="space-y-1.5 text-sm"><span>Period</span><select aria-label="Report period" className={inputClass} onChange={(event) => { setPreset(event.target.value as ReportPeriodPreset); setPage(1) }} value={preset}>{presets.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{preset === "custom" && <><label className="space-y-1.5 text-sm"><span>Start date</span><input aria-label="Report start date" className={inputClass} onChange={(event) => { setCustomStart(event.target.value); setPage(1) }} type="date" value={customStart} /></label><label className="space-y-1.5 text-sm"><span>End date</span><input aria-label="Report end date" className={inputClass} onChange={(event) => { setCustomEnd(event.target.value); setPage(1) }} type="date" value={customEnd} /></label></>}</section>
    <div className="hidden print:block"><p className="text-sm text-muted-foreground">{business?.name} · {range ? `${range.startDate} – ${range.endDate}` : "Invalid period"} · Generated {new Date().toLocaleString()}</p></div>
    {!range && <p className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-sm" role="status">Choose a valid date range. Custom ranges must be ordered, cannot include future dates, and are limited to 366 calendar days.</p>}
    {report.isLoading && <p className="rounded-xl border p-8 text-center text-muted-foreground" role="status">Loading report…</p>}
    {report.isError && <div className="rounded-xl border border-destructive/25 p-8 text-center" role="alert">{report.error.message}<Button className="ml-3" onClick={() => void report.refetch()} size="sm" variant="outline">Retry</Button></div>}
    {report.data && <><div className="print-report-header"><p className="text-sm font-medium text-primary">{labels[type]}</p><h2 className="mt-1 text-2xl font-semibold">{business?.name}</h2><p className="mt-1 text-sm text-muted-foreground">Business dates: {report.data.startDate} – {report.data.endDate}</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(report.data.summary).map(([key, value]) => <div className="rounded-xl border bg-card p-4" key={key}><p className="text-xs capitalize text-muted-foreground">{key.replace(/([A-Z])/g, " $1")}</p><p className="mt-2 break-all font-semibold tabular-nums">{value === null ? "Unavailable" : String(value)}</p></div>)}</div>{report.data.rows.length === 0 ? <p className="rounded-xl border border-dashed p-8 text-center text-muted-foreground">No recorded data in this period.</p> : <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/60 text-xs uppercase tracking-wide text-muted-foreground"><tr>{columns.map((column) => <th className="whitespace-nowrap px-4 py-3 font-medium" key={column.key}>{column.label}</th>)}</tr></thead><tbody className="divide-y">{report.data.rows.map((row, index) => <tr key={index}>{columns.map((column) => <td className="max-w-xs px-4 py-3 align-top" key={column.key}>{row[column.key] === null ? "—" : String(row[column.key])}</td>)}</tr>)}</tbody></table></div>}{report.data.totalRows > report.data.pageSize && <div className="flex items-center justify-between print:hidden"><p className="text-sm text-muted-foreground">Showing page {report.data.page} of {Math.ceil(report.data.totalRows / report.data.pageSize)}</p><div className="flex gap-2"><Button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} variant="outline">Previous</Button><Button disabled={page >= Math.ceil(report.data.totalRows / report.data.pageSize)} onClick={() => setPage((value) => value + 1)} variant="outline">Next</Button></div></div>}</>}
  </section>
}
