import { useState, type FormEvent } from "react"
import { Button } from "@/components/ui/button"
import { useAcceptTeamInvitation } from "@/features/team/team-queries"
import { TeamDataError } from "@/features/team/team-types"

export function TeamInvitationAcceptancePage() {
  const [invitationId, setInvitationId] = useState(""); const [error, setError] = useState(""); const [status, setStatus] = useState(""); const mutation = useAcceptTeamInvitation()
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setStatus(""); if (!invitationId.trim()) { setError("Enter the invitation ID provided by your business administrator."); return } try { await mutation.mutateAsync(invitationId.trim()); setStatus("Invitation accepted. Refresh your workspace to load the new membership."); setInvitationId("") } catch (cause) { setError(cause instanceof TeamDataError ? cause.message : "We couldn't accept this invitation.") } }
  return <section aria-labelledby="accept-invitation-heading" className="mx-auto max-w-xl space-y-6"><header><p className="text-sm font-medium text-primary">Team invitation</p><h1 className="mt-1 text-3xl font-semibold tracking-tight" id="accept-invitation-heading">Accept an invitation</h1><p className="mt-2 text-muted-foreground">Acceptance is limited to the authenticated account whose verified email matches the invitation. StockPilot does not use bearer invitation links.</p></header><form className="rounded-xl border border-border bg-card p-5 shadow-sm" onSubmit={(event) => { void submit(event) }}><label className="block space-y-1.5 text-sm"><span className="font-medium">Invitation ID</span><input className="h-10 w-full rounded-md border border-border bg-background px-3 font-mono text-sm outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/20" disabled={mutation.isPending} onChange={(event) => setInvitationId(event.target.value)} placeholder="Invitation ID" value={invitationId} /></label><Button className="mt-4" disabled={mutation.isPending || !invitationId.trim()} type="submit">{mutation.isPending ? "Accepting…" : "Accept invitation"}</Button>{error && <p className="mt-4 rounded-lg border border-destructive/25 bg-destructive/5 p-3 text-sm text-destructive" role="alert">{error}</p>}{status && <p className="mt-4 rounded-lg border border-primary/20 bg-primary/5 p-3 text-sm" role="status">{status}</p>}</form></section>
}
