import { render, screen } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { beforeEach, describe, expect, it, vi } from "vitest"
import { TestAuthProvider, TestBusinessProvider, createAuthValue, createBusinessValue, testBusiness, testSession, testUser } from "@/test/auth-test-utils"

const mocks = vi.hoisted(() => ({ useTeam: vi.fn(), useMutations: vi.fn() }))
vi.mock("@/features/team/team-queries", () => ({ useTeamAdministration: mocks.useTeam, useTeamMutations: mocks.useMutations }))
import { TeamPage } from "./team-page"

const member = (overrides: Record<string, unknown> = {}) => ({ membershipId: "m1", userId: "member-1", displayName: "Jamie Member", email: "jamie@example.com", role: "employee", status: "active", createdAt: "2026-01-01T00:00:00Z", updatedAt: "2026-01-01T00:00:00Z", statusChangedAt: null, ...overrides })
const invitation = { invitationId: "i1", email: "pending@example.com", role: "employee", status: "pending", invitedBy: "owner-1", createdAt: "2026-01-01T00:00:00Z", expiresAt: "2026-01-08T00:00:00Z", acceptedAt: null, revokedAt: null }
const data = { schemaVersion: 1 as const, businessId: "business-1", callerRole: "owner" as const, members: [member({ membershipId: "owner", userId: testUser.id, displayName: "Alex Owner", role: "owner" }), member()], invitations: [invitation] }
function renderPage(role: "owner" | "manager" | "employee" | "cashier" = "owner", modules: Array<"team"> = ["team"]) { return render(<TestAuthProvider value={createAuthValue({ session: testSession, user: testUser })}><TestBusinessProvider value={createBusinessValue({ business: testBusiness, role, enabledModules: modules })}><TeamPage /></TestBusinessProvider></TestAuthProvider>) }
function mutation() { return { isPending: false, mutateAsync: vi.fn().mockResolvedValue({}) } }

describe("TeamPage", () => {
  beforeEach(() => { mocks.useTeam.mockReturnValue({ data, isLoading: false, isError: false, error: null, refetch: vi.fn() }); mocks.useMutations.mockReturnValue({ invite: mutation(), revoke: mutation(), changeRole: mutation(), setActive: mutation() }) })
  it("renders active members, pending invitations, and inactive members", () => { mocks.useTeam.mockReturnValue({ data: { ...data, members: [member(), member({ membershipId: "m2", displayName: "Inactive", status: "inactive" })] }, isLoading: false, isError: false }); renderPage(); expect(screen.getByRole("heading", { name: "Team" })).toBeInTheDocument(); expect(screen.getByText("Jamie Member")).toBeInTheDocument(); expect(screen.getByRole("heading", { name: "Inactive" })).toBeInTheDocument(); expect(screen.getByText("pending@example.com")).toBeInTheDocument() })
  it("offers all invite roles to owners and submits the RPC-backed invitation", async () => { const user = userEvent.setup(); renderPage(); const role = screen.getAllByRole("combobox")[0]; expect(role).toHaveDisplayValue("Manager"); expect(screen.getAllByRole("option", { name: "Cashier" })).not.toHaveLength(0); await user.type(screen.getByLabelText("Email"), "new@example.com"); await user.click(screen.getByRole("button", { name: "Invite member" })); expect(mocks.useMutations.mock.results[0].value.invite.mutateAsync).toHaveBeenCalledWith({ email: "new@example.com", role: "manager" }) })
  it("restricts manager invite roles and protects owner management actions", () => { mocks.useTeam.mockReturnValue({ data: { ...data, callerRole: "manager", members: [member({ userId: testUser.id, displayName: "Manager", role: "manager" }), member({ membershipId: "owner", userId: "owner-2", displayName: "Owner", role: "owner" })] }, isLoading: false, isError: false }); renderPage("manager"); expect(screen.queryByRole("option", { name: "Manager" })).not.toBeInTheDocument(); expect(screen.getByLabelText("Owner role")).toBeDisabled(); expect(screen.getByText("Owner membership is protected.")).toBeInTheDocument() })
  it("supports revoke, role change, and deactivation without duplicate submissions", async () => { const user = userEvent.setup(); const mutations = { invite: mutation(), revoke: mutation(), changeRole: mutation(), setActive: mutation() }; mocks.useMutations.mockReturnValue(mutations); vi.spyOn(window, "confirm").mockReturnValue(true); renderPage(); await user.click(screen.getByRole("button", { name: "Revoke" })); expect(mutations.revoke.mutateAsync).toHaveBeenCalledWith("i1"); const roleSelect = screen.getByLabelText("Jamie Member role"); await user.selectOptions(roleSelect, "manager"); expect(mutations.changeRole.mutateAsync).toHaveBeenCalledWith({ membershipId: "m1", role: "manager" }); await user.click(screen.getByRole("button", { name: "Deactivate" })); expect(mutations.setActive.mutateAsync).toHaveBeenCalledWith({ membershipId: "m1", active: false }) })
  it.each(["employee", "cashier"] as const)("does not render admin UI for %s", (role) => { renderPage(role); expect(screen.queryByRole("heading", { name: "Team" })).not.toBeInTheDocument() })
  it("does not render when Team is disabled", () => { renderPage("owner", []); expect(screen.queryByRole("heading", { name: "Team" })).not.toBeInTheDocument() })
})
