import { useState, type FormEvent } from "react"
import { Button } from "@/components/ui/button"
import { useAuth } from "@/features/auth/auth-context"
import { useBusiness } from "@/features/business/business-context"
import { useTeamAdministration, useTeamMutations } from "@/features/team/team-queries"
import { TeamDataError, type TeamInvitation, type TeamMember, type TeamRole } from "@/features/team/team-types"

const roles: Array<Exclude<TeamRole, "owner">> = ["manager", "employee", "cashier"]
const roleLabels: Record<TeamRole, string> = { owner: "Owner", manager: "Manager", employee: "Employee", cashier: "Cashier" }
const statusLabels: Record<TeamMember["status"], string> = { active: "Active", inactive: "Inactive", suspended: "Suspended" }
const inputClass = "h-10 w-full rounded-md border border-border bg-background px-3 text-sm outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/20"

export function TeamPage() {
  const { business, enabledModules, role } = useBusiness(); const { user } = useAuth(); const query = useTeamAdministration(); const mutations = useTeamMutations()
  const [email, setEmail] = useState(""); const [inviteRole, setInviteRole] = useState<Exclude<TeamRole, "owner">>(role === "manager" ? "employee" : "manager"); const [error, setError] = useState(""); const [status, setStatus] = useState("")
  const pendingMutation = mutations.invite.isPending || mutations.revoke.isPending || mutations.changeRole.isPending || mutations.setActive.isPending
  const inviteRoles = query.data?.callerRole === "manager" ? roles.filter((item) => item !== "manager") : roles

  const invite = async (event: FormEvent) => {
    event.preventDefault(); setError(""); setStatus(""); const normalized = email.trim().toLowerCase()
    if (!business || !/^\S+@\S+\.\S+$/.test(normalized)) { setError("Enter a valid email address."); return }
    try { await mutations.invite.mutateAsync({ email: normalized, role: inviteRole }); setEmail(""); setStatus("Invitation created. The invited verified account must accept it before joining the team.") }
    catch (cause) { setError(cause instanceof TeamDataError ? cause.message : "We couldn't create the invitation.") }
  }
  const mutate = async (action: () => Promise<unknown>, success: string) => { setError(""); setStatus(""); try { await action(); setStatus(success) } catch (cause) { setError(cause instanceof TeamDataError ? cause.message : "We couldn't update the team.") } }

  if (!business || !enabledModules.includes("team") || !["owner", "manager"].includes(role ?? "")) return null
  return <section aria-labelledby="team-heading" className="space-y-6">
    <header><p className="text-sm font-medium text-primary">Workspace administration</p><h1 className="mt-1 text-3xl font-semibold tracking-tight" id="team-heading">Team</h1><p className="mt-2 max-w-2xl text-muted-foreground">Manage active memberships and invitations for this business. Invitations are pending until the invited verified account accepts them.</p></header>
    {query.isLoading && <div className="flex min-h-48 items-center justify-center rounded-xl border border-border bg-card" role="status">Loading Team…</div>}
    {query.isError && !query.isLoading && <div className="rounded-xl border border-destructive/25 bg-card p-8 text-center" role="alert"><h2 className="text-lg font-semibold">Team unavailable</h2><p className="mt-2 text-muted-foreground">{query.error instanceof Error ? query.error.message : "We couldn't load the Team directory."}</p><Button className="mt-5" onClick={() => void query.refetch()} variant="outline">Try again</Button></div>}
    {query.data && !query.isError && <>
      <section aria-labelledby="invite-heading" className="rounded-xl border border-border bg-card p-5 shadow-sm sm:p-6"><div><h2 className="font-semibold" id="invite-heading">Invite a member</h2><p className="mt-1 text-sm text-muted-foreground">No email is sent by StockPilot in this phase. Share the invitation through your normal process; acceptance still requires the matching verified account.</p></div><form className="mt-5 grid gap-4 sm:grid-cols-[minmax(0,1fr)_12rem_auto] sm:items-end" noValidate onSubmit={(event) => { void invite(event) }}><label className="space-y-1.5 text-sm"><span className="font-medium">Email</span><input autoComplete="email" className={inputClass} disabled={pendingMutation} onChange={(event) => setEmail(event.target.value)} placeholder="name@example.com" type="email" value={email} /></label><label className="space-y-1.5 text-sm"><span className="font-medium">Role</span><select className={inputClass} disabled={pendingMutation} onChange={(event) => setInviteRole(event.target.value as Exclude<TeamRole, "owner">)} value={inviteRole}>{inviteRoles.map((item) => <option key={item} value={item}>{roleLabels[item]}</option>)}</select></label><Button disabled={pendingMutation || !email.trim()} type="submit">{mutations.invite.isPending ? "Inviting…" : "Invite member"}</Button></form>{error && <p className="mt-4 rounded-lg border border-destructive/25 bg-destructive/5 p-3 text-sm text-destructive" role="alert">{error}</p>}{status && <p className="mt-4 rounded-lg border border-primary/20 bg-primary/5 p-3 text-sm" role="status">{status}</p>}</section>
      <section aria-labelledby="members-heading" className="space-y-3"><div className="flex items-end justify-between gap-3"><div><h2 className="font-semibold" id="members-heading">Members</h2><p className="mt-1 text-sm text-muted-foreground">Owner protection and role permissions are enforced by the backend.</p></div><span className="text-sm text-muted-foreground">{query.data.members.length} member{query.data.members.length === 1 ? "" : "s"}</span></div>{query.data.members.length === 0 ? <Empty text="No members are currently listed." /> : <div className="space-y-3">{query.data.members.map((member) => <MemberCard key={member.membershipId} member={member} currentUserId={user?.id ?? ""} callerRole={query.data?.callerRole ?? "manager"} disabled={pendingMutation} onRoleChange={(newRole) => void mutate(() => mutations.changeRole.mutateAsync({ membershipId: member.membershipId, role: newRole }), `${member.displayName}'s role was updated.`)} onStatusChange={(active) => void mutate(() => mutations.setActive.mutateAsync({ membershipId: member.membershipId, active }), active ? `${member.displayName} was reactivated.` : `${member.displayName} was deactivated.`)} />)}</div>}</section>
      <InvitationSection invitations={query.data.invitations} callerRole={query.data.callerRole} disabled={pendingMutation} onRevoke={(invitation) => { if (window.confirm(`Revoke the invitation for ${invitation.email}?`)) void mutate(() => mutations.revoke.mutateAsync(invitation.invitationId), "Invitation revoked.") }} />
    </>}
  </section>
}

function MemberCard({ member, currentUserId, callerRole, disabled, onRoleChange, onStatusChange }: { member: TeamMember; currentUserId: string; callerRole: "owner" | "manager"; disabled: boolean; onRoleChange: (role: Exclude<TeamRole, "owner">) => void; onStatusChange: (active: boolean) => void }) {
  const self = member.userId === currentUserId; const manageable = !self && member.role !== "owner" && (callerRole === "owner" || ["employee", "cashier"].includes(member.role)); const roleOptions = callerRole === "manager" ? ["employee", "cashier"] as const : ["manager", "employee", "cashier"] as const
  return <article className="rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><h3 className="truncate font-semibold">{member.displayName}</h3><p className="mt-1 break-all text-sm text-muted-foreground">{member.email ?? "Email unavailable"}</p><p className="mt-1 text-xs text-muted-foreground">Joined {formatDate(member.createdAt)}</p></div><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium ${member.status === "active" ? "border-primary/25 bg-primary/5 text-primary" : "border-border bg-muted text-muted-foreground"}`}>{statusLabels[member.status]}</span></div><div className="mt-4 flex flex-col gap-3 border-t border-border pt-4 sm:flex-row sm:items-end sm:justify-between"><label className="space-y-1.5 text-sm"><span className="text-xs text-muted-foreground">Role</span><select aria-label={`${member.displayName} role`} className="h-9 rounded-md border border-border bg-background px-2 text-sm" disabled={!manageable || disabled} onChange={(event) => onRoleChange(event.target.value as Exclude<TeamRole, "owner">)} value={member.role}>{member.role === "owner" && <option value="owner">Owner</option>}{roleOptions.map((item) => <option key={item} value={item}>{roleLabels[item]}</option>)}</select></label>{manageable && <Button disabled={disabled} onClick={() => { if (window.confirm(`${member.status === "active" ? "Deactivate" : "Reactivate"} ${member.displayName}?`)) onStatusChange(member.status !== "active") }} variant="outline">{member.status === "active" ? "Deactivate" : "Reactivate"}</Button>}{self && <span className="text-xs text-muted-foreground">Your own membership cannot be changed here.</span>}{member.role === "owner" && !self && <span className="text-xs text-muted-foreground">Owner membership is protected.</span>}</div></article>
}

function InvitationSection({ invitations, callerRole, disabled, onRevoke }: { invitations: TeamInvitation[]; callerRole: "owner" | "manager"; disabled: boolean; onRevoke: (invitation: TeamInvitation) => void }) { const pending = invitations.filter((item) => item.status === "pending"); const history = invitations.filter((item) => item.status !== "pending"); return <section aria-labelledby="invitations-heading" className="space-y-3"><div><h2 className="font-semibold" id="invitations-heading">Invitations</h2><p className="mt-1 text-sm text-muted-foreground">Pending invitations require acceptance by the matching verified account.</p></div>{pending.length === 0 ? <Empty text="No pending invitations." /> : <div className="space-y-3">{pending.map((invitation) => <InvitationCard key={invitation.invitationId} invitation={invitation} callerRole={callerRole} disabled={disabled} onRevoke={onRevoke} />)}</div>}{history.length > 0 && <details className="rounded-xl border border-border bg-card p-4"><summary className="cursor-pointer text-sm font-medium">Past invitations ({history.length})</summary><div className="mt-3 space-y-2">{history.map((invitation) => <div className="flex flex-wrap items-center justify-between gap-2 border-t border-border pt-3 text-sm" key={invitation.invitationId}><span>{invitation.email} · {roleLabels[invitation.role]}</span><span className="text-muted-foreground">{invitation.status}</span></div>)}</div></details>}</section> }
function InvitationCard({ invitation, callerRole, disabled, onRevoke }: { invitation: TeamInvitation; callerRole: "owner" | "manager"; disabled: boolean; onRevoke: (invitation: TeamInvitation) => void }) { const canRevoke = callerRole === "owner" || ["employee", "cashier"].includes(invitation.role); return <article className="flex flex-col gap-3 rounded-xl border border-dashed border-border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{invitation.email}</p><p className="mt-1 text-sm text-muted-foreground">{roleLabels[invitation.role]} · Created {formatDate(invitation.createdAt)} · Expires {formatDate(invitation.expiresAt)}</p></div>{canRevoke && <Button disabled={disabled} onClick={() => onRevoke(invitation)} variant="outline">{disabled ? "Updating…" : "Revoke"}</Button>}</article> }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-border bg-card p-6 text-center text-sm text-muted-foreground">{text}</div> }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(date) }
